"""add playlist models

Revision ID: a55c80b1dcbf
Revises: 
Create Date: 2026-06-12 17:29:42.788446

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a55c80b1dcbf'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist_name', sa.String(length=500), nullable=False),
    sa.Column('album_name', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('isrc', sa.String(length=32), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_external_id'), 'tracks', ['external_id'], unique=True)
    op.create_index(op.f('ix_tracks_isrc'), 'tracks', ['isrc'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('playlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('total_tracks', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_external_id'), 'playlists', ['external_id'], unique=False)
    op.create_index(op.f('ix_playlists_owner_id'), 'playlists', ['owner_id'], unique=False)
    op.create_table('spotify_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=255), nullable=False, comment="Spotify's own user ID (e.g. '31xyz...')"),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=False, comment='UTC datetime when the access_token expires'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotify_accounts_spotify_user_id'), 'spotify_accounts', ['spotify_user_id'], unique=True)
    op.create_index(op.f('ix_spotify_accounts_user_id'), 'spotify_accounts', ['user_id'], unique=True)
    op.create_table('playlist_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'track_id', name='uq_playlist_track')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_tracks')
    op.drop_index(op.f('ix_spotify_accounts_user_id'), table_name='spotify_accounts')
    op.drop_index(op.f('ix_spotify_accounts_spotify_user_id'), table_name='spotify_accounts')
    op.drop_table('spotify_accounts')
    op.drop_index(op.f('ix_playlists_owner_id'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_external_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tracks_isrc'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_external_id'), table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
